# Generated by Django 6.0.3 on 2026-03-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
    ]
