# Generated by Django 6.0.3 on 2026-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_alter_session_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatreservation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
